#!/bin/bash

# If Clean.gba does not exist, throw an error
if [ ! -f "Clean.gba" ]; then
  echo "Clean.gba not found. Please place a clean ROM in the same directory as this script."
  exit 1
fi

currDir="$(cd "$(dirname "$0")" && pwd)"

echo "-----------------------------------"
echo "Assembling assets... Please wait..."
echo "-----------------------------------"

# Assemble autogenerated definitions
echo "Assembling autogenerated definitions..."
cd "$currDir"
./AssembleDefs.sh noPause

# Assemble graphics
cd "$currDir"
./AssembleGraphics.sh noPause

# Assemble tables
echo "Assembling tables..."
cd "$currDir"
./AssembleTables.sh noPause

# Assemble text
echo "Assembling text..."
cd "$currDir"
./AssembleText.sh noPause

# Assemble music
echo "Assembling music..."
cd "$currDir"
./AssembleMusic.sh noPause noRefs

# Assemble maps
echo "Assembling maps..."
cd "$currDir"
./AssembleMaps.sh noPause

# Make animations
cd "$currDir"
# ./MAKEAnims.sh noPause
wine cmd /c MAKEAnims.bat noPause

# Final make
cd "$currDir"
# ./MAKEHACK.sh noPause noSaveCopy
wine cmd /c MAKEHACK.bat noPause noSaveCopy
