
@echo off
setlocal enabledelayedexpansion

@REM if Clean.gba does not exist, throw an error
if not exist "Clean.gba" (
    echo Clean.gba not found. Please place a clean ROM in the same directory as this script.
    exit
)

set currDir=%~dp0

echo -----------------------------------
echo Assembling assets... Please wait...
echo -----------------------------------


cd "!currDir!"

echo Assembling autogenerated definitions...

call "AssembleDefs.bat" noPause


cd "!currDir!"

call "AssembleGraphics.bat" noPause


cd "!currDir!"

echo Assembling tables...

call "AssembleTables.bat" noPause


cd "!currDir!"

echo Assembling text...

call "AssembleText.bat" noPause


cd "!currDir!"

echo Assembling music...

call "AssembleMusic.bat" noPause noRefs


cd "!currDir!"
echo Assembling maps...

call "AssembleMaps.bat" noPause


cd "!currDir!"

call "MAKEAnims.bat" noPause


cd "!currDir!"

call "MAKEHACK.bat" noPause noSaveCopy
