export const characterTableCsvHeaders = [
  "", // empty
  "Name",
  "Description",
  "Character Number",
  "Default Class",
  "Portrait",
  "Mini Portrait",
  "Affinity",
  "", // empty
  "Base Level",
  "Base HP",
  "Base Pwr",
  "Base Magic",
  "Base Skl",
  "Base Spd",
  "Base Def",
  "Base Res",
  "Base Lck",
  "Base Con",
  "Sword Rank",
  "Lance Rank",
  "Axe Rank",
  "Bow Rank",
  "Staff Rank",
  "Anima Rank",
  "Light Rank",
  "Dark Rank",
  "HP Growth",
  "Pwr Growth",
  "Magic Growth",
  "Skl Growth",
  "Spd Growth",
  "Def Growth",
  "Res Growth",
  "Lck Growth",
  "Level Up Skill List",
  "Personal Skill",
  "Escape Quote",
  "", // empty
  "Character Ability 1",
  "Character Ability 2",
  "Character Ability 3",
  "Character Ability 4",
  "Support Data Pointer",
  "", // empty
  "", // empty
  "", // empty
  "CharacterTableUnknown10",
  "CharacterTableUnknown35",
  "CharacterTableUnknown48",
];
