import type { PortraitMetadata } from "@/types/PortraitMetadata.ts";

export const allPortraitOptions: PortraitMetadata[] = [
  {
    originalImageName: "0.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "teal",
    eyeColor: "purple",
    vibe: "mystical, serene, confident",
    clothing: "white dress with purple accents",
    accessories: "necklace",
  },
  {
    originalImageName: "1.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "red",
    eyeColor: "unknown",
    vibe: "confident, adventurous, charismatic",
    clothing: "cloak with fur trim",
    accessories: "none",
  },
  {
    originalImageName: "2.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "pink",
    eyeColor: "blue",
    vibe: "elegant, serene, confident",
    clothing: "elegant dress",
    accessories: "headpiece",
  },
  {
    originalImageName: "3.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "mysterious, elegant, confident",
    clothing: "elegant dress",
    accessories: "headband",
  },
  {
    originalImageName: "4.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "green",
    vibe: "gentle, cheerful, hopeful",
    clothing: "green dress",
    accessories: "hair flower",
  },
  {
    originalImageName: "5.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "silver",
    eyeColor: "green",
    vibe: "calm, serene, thoughtful",
    clothing: "green attire",
    accessories: "leaf hairpin",
  },
  {
    originalImageName: "6.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "green",
    vibe: "calm, serene, gentle",
    clothing: "green scarf, dark top",
    accessories: "hairpin",
  },
  {
    originalImageName: "7.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "brown",
    vibe: "friendly, adventurous, confident",
    clothing: "purple top with a scarf",
  },
  {
    originalImageName: "8.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "purple",
    vibe: "calm, noble, determined",
    clothing: "white robe with gold accents",
    headgear: "headband",
  },
  {
    originalImageName: "9.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "blue",
    vibe: "elegant, thoughtful, serene",
    clothing: "purple dress with blue accents",
    accessories: "headband",
  },
  {
    originalImageName: "10.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "blue",
    vibe: "determined, noble, thoughtful",
    clothing: "blue and gold armor",
    accessories: "brooch",
  },
  {
    originalImageName: "11.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "pink",
    eyeColor: "purple",
    vibe: "soft, gentle, thoughtful",
    clothing: "casual, modern, stylish",
    accessories: "choker",
  },
  {
    originalImageName: "12.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "red",
    vibe: "regal, determined, graceful",
    clothing: "armor with a pink accent",
    accessories: "floral headpiece",
  },
  {
    originalImageName: "13.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "brown",
    vibe: "elegant, mysterious, confident",
    clothing: "dark dress with gold accents",
    accessories: "earrings, headpiece",
  },
  {
    originalImageName: "14.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "orange",
    eyeColor: "unknown",
    vibe: "confident, elegant, mysterious",
    clothing: "pink attire",
    accessories: "earrings, headband",
  },
  {
    originalImageName: "15.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "calm, determined, wise",
    clothing: "elegant robe with ornate details",
    accessories: "earrings",
  },
  {
    originalImageName: "16.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "green",
    vibe: "confident, adventurous, charismatic",
    clothing: "green cloak, casual shirt",
  },
  {
    originalImageName: "17.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "dark gray",
    eyeColor: "brown",
    vibe: "confident, charismatic, adventurous",
    clothing: "red cloak, casual shirt",
  },
  {
    originalImageName: "18.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "green",
    vibe: "mysterious, elegant, serene",
    clothing: "purple robe",
    accessories: "necklace",
  },
  {
    originalImageName: "19.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "green",
    vibe: "determined, confident, approachable",
    clothing: "armor with a scarf",
  },
  {
    originalImageName: "20.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "unknown",
    vibe: "determined, confident, strong",
    clothing: "purple cloak",
    accessories: "earrings",
  },
  {
    originalImageName: "21.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "light blue",
    eyeColor: "purple",
    vibe: "elegant, serene, mystical",
    clothing: "purple dress",
    accessories: "headpiece",
  },
  {
    originalImageName: "22.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "red",
    eyeColor: "green",
    vibe: "mysterious, confident, noble",
    clothing: "purple and red armor",
    accessories: "none",
  },
  {
    originalImageName: "23.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "unknown",
    vibe: "confident, stylish, determined",
    clothing: "red hat, purple cloak",
    headgear: "red hat",
  },
  {
    originalImageName: "24.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "purple",
    vibe: "elegant, serene, mystical",
    clothing: "purple dress with flowing sleeves",
    accessories: "headband",
  },
  {
    originalImageName: "25.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "unknown",
    vibe: "confident, sly, playful",
    clothing: "dark outfit with a scarf",
    accessories: "none",
  },
  {
    originalImageName: "26.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "blue",
    vibe: "confident, alluring, stylish",
    clothing: "blue scarf, casual attire",
  },
  {
    originalImageName: "27.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "blue",
    vibe: "calm, thoughtful, gentle",
    clothing: "colorful attire",
  },
  {
    originalImageName: "28.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "green",
    vibe: "mysterious, confident, elegant",
    clothing: "purple and gold attire",
    accessories: "hair clips",
  },
  {
    originalImageName: "29.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "unknown",
    vibe: "confident, playful, spirited",
    clothing: "blue outfit with gold accents",
    accessories: "earrings",
  },
  {
    originalImageName: "30.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "red",
    vibe: "mysterious, confident, elegant",
    clothing: "purple and gray attire",
    accessories: "earrings",
  },
  {
    originalImageName: "31.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "silver",
    eyeColor: "red",
    vibe: "mysterious, elegant, intense",
    clothing: "dark hooded cloak",
    accessories: "headband",
  },
  {
    originalImageName: "32.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "pink",
    eyeColor: "unknown",
    vibe: "cheerful, friendly, vibrant",
    clothing: "green outfit",
  },
  {
    originalImageName: "33.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "red",
    vibe: "determined, fierce, confident",
    clothing: "armor with a red sash",
    accessories: "headband",
  },
  {
    originalImageName: "34.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "blue",
    vibe: "mysterious, calm, confident",
    clothing: "hooded cloak",
  },
  {
    originalImageName: "35.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "unknown",
    vibe: "confident, adventurous, cool",
    clothing: "casual tunic with a bandana",
    accessories: "earring",
  },
  {
    originalImageName: "36.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "blue",
    vibe: "confident, mysterious, noble",
    clothing: "dark cloak with a blue tunic",
    accessories: "headband",
  },
  {
    originalImageName: "37.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "red",
    eyeColor: "unknown",
    vibe: "confident, determined, strategic",
    clothing: "blue cloak with intricate designs",
    headgear: "hat",
    accessories: "none",
  },
  {
    originalImageName: "38.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "mysterious, calm, focused",
    clothing: "hooded cloak",
    accessories: "necklace",
  },
  {
    originalImageName: "39.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "purple",
    vibe: "playful, cheerful, friendly",
    clothing: "purple dress",
  },
  {
    originalImageName: "40.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "blue",
    vibe: "calm, serene, thoughtful",
    clothing: "blue cloak",
  },
  {
    originalImageName: "41.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "blue",
    vibe: "confident, heroic, determined",
    clothing: "armor",
  },
  {
    originalImageName: "42.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "unknown",
    vibe: "mysterious, confident, elegant",
    clothing: "red cloak",
    accessories: "none",
  },
  {
    originalImageName: "43.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "mature adult",
    hairColor: "brown",
    eyeColor: "unknown",
    vibe: "strong, noble, determined",
    clothing: "armor with blue accents",
    accessories: "none",
  },
  {
    originalImageName: "44.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "blue",
    vibe: "thoughtful, cheerful, playful",
    clothing: "purple top with shoulder cutouts",
    accessories: "pink headband",
  },
  {
    originalImageName: "45.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "elderly",
    hairColor: "white",
    eyeColor: "unknown",
    vibe: "wise, serene, contemplative",
    clothing: "brown robe",
    facialHair: "long white beard",
  },
  {
    originalImageName: "46.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "unknown",
    vibe: "elegant, serene, mystical",
    clothing: "pink dress",
    accessories: "necklace",
  },
  {
    originalImageName: "47.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "determined, confident, focused",
    clothing: "red military uniform",
  },
  {
    originalImageName: "48.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "mysterious, calm, focused",
    clothing: "hooded cloak",
  },
  {
    originalImageName: "49.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "dark gray",
    eyeColor: "blue",
    vibe: "confident, determined, friendly",
    clothing: "blue cloak with armor",
    accessories: "none",
  },
  {
    originalImageName: "50.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "blue",
    vibe: "calm, thoughtful, serene",
    clothing: "blue dress",
    accessories: "earrings",
  },
  {
    originalImageName: "51.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "blue",
    vibe: "thoughtful, introspective, determined",
    clothing: "purple cloak with a green scarf",
    accessories: "glasses",
  },
  {
    originalImageName: "52.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "unknown",
    vibe: "calm, thoughtful, determined",
    clothing: "purple tunic with a green necklace",
  },
  {
    originalImageName: "53.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "unknown",
    vibe: "elegant, serene, confident",
    clothing: "purple dress",
    accessories: "hair ornament",
  },
  {
    originalImageName: "54.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "green",
    vibe: "thoughtful, confident, playful",
    clothing: "colorful outfit with fur accents",
    accessories: "earrings",
  },
  {
    originalImageName: "55.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "brown",
    eyeColor: "blue",
    vibe: "confident, friendly, adventurous",
    clothing: "white top with blue accents",
    accessories: "earrings",
  },
  {
    originalImageName: "56.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "red",
    eyeColor: "blue",
    vibe: "confident, determined, adventurous",
    clothing: "stylish armor",
    accessories: "feather hairpin",
  },
  {
    originalImageName: "57.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "unknown",
    vibe: "confident, calm, noble",
    clothing: "green cloak",
    accessories: "earrings",
  },
  {
    originalImageName: "58.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blue",
    eyeColor: "unknown",
    vibe: "playful, determined, adventurous",
    clothing: "scarf and casual attire",
  },
  {
    originalImageName: "59.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "gray",
    eyeColor: "blue",
    vibe: "calm, confident, graceful",
    clothing: "elegant dress",
    accessories: "necklace",
  },
  {
    originalImageName: "60.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "gray",
    eyeColor: "red",
    vibe: "mysterious, confident, elegant",
    clothing: "blue dress",
  },
  {
    originalImageName: "61.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "red",
    eyeColor: "purple",
    vibe: "cheerful, friendly, vibrant",
    clothing: "casual, colorful outfit",
    accessories: "hair bow",
  },
  {
    originalImageName: "62.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "blue",
    vibe: "cheerful, friendly, artistic",
    clothing: "colorful outfit",
    accessories: "earring",
  },
  {
    originalImageName: "63.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "red",
    eyeColor: "blue",
    vibe: "confident, charismatic, bold",
    clothing: "dark vest with high collar",
  },
  {
    originalImageName: "64.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "dark brown",
    eyeColor: "brown",
    vibe: "elegant, confident, friendly",
    clothing: "purple and white attire",
    accessories: "earrings",
  },
  {
    originalImageName: "65.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "green",
    vibe: "confident, heroic, determined",
    clothing: "green cloak, armor",
  },
  {
    originalImageName: "66.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "silver",
    eyeColor: "red",
    vibe: "mysterious, elegant, powerful",
    clothing: "dark cloak with intricate designs",
    accessories: "ornate headpiece",
  },
  {
    originalImageName: "67.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "green",
    eyeColor: "green",
    vibe: "confident, graceful, serene",
    clothing: "red dress with floral accents",
    accessories: "rose in hair",
  },
  {
    originalImageName: "68.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "red",
    vibe: "elegant, mysterious, confident",
    clothing: "purple dress",
    accessories: "necklace",
  },
  {
    originalImageName: "69.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "cheerful, friendly, lively",
    clothing: "green outfit",
    accessories: "headband",
  },
  {
    originalImageName: "70.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "determined, graceful, thoughtful",
    clothing: "traditional attire",
    accessories: "headband",
  },
  {
    originalImageName: "71.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "blue",
    vibe: "elegant, confident, mysterious",
    clothing: "blue cloak with gold accents",
    accessories: "earring",
  },
  {
    originalImageName: "72.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "blue",
    vibe: "confident, mysterious, elegant",
    clothing: "blue and black outfit",
  },
  {
    originalImageName: "73.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "purple",
    vibe: "confident, vibrant, spirited",
    clothing: "red and gold outfit",
    accessories: "earrings, headband",
  },
  {
    originalImageName: "74.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "unknown",
    vibe: "confident, cheerful, regal",
    clothing: "red and green outfit with a crown",
    accessories: "wings, jewelry",
  },
  {
    originalImageName: "75.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "red",
    eyeColor: "blue",
    vibe: "elegant, cheerful, whimsical",
    clothing: "dress with lace",
    accessories: "necklace",
  },
  {
    originalImageName: "76.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "purple",
    eyeColor: "unknown",
    vibe: "confident, playful, spirited",
    clothing: "purple outfit with gold accents",
    headgear: "purple headband",
  },
  {
    originalImageName: "77.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "pink",
    eyeColor: "brown",
    vibe: "mysterious, serene, thoughtful",
    clothing: "hooded cloak",
    headgear: "hood",
  },
  {
    originalImageName: "78.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "male",
    age: "young adult",
    hairColor: "blonde",
    eyeColor: "unknown",
    vibe: "charming, confident, mysterious",
    clothing: "red robe",
    accessories: "book",
  },
  {
    originalImageName: "79.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "black",
    eyeColor: "brown",
    vibe: "elegant, cheerful, vibrant",
    clothing: "traditional attire",
    accessories: "earrings, flower in hair",
  },
  {
    originalImageName: "80.png",
    eyeMouthOffsets: {
      eyeX: 3,
      eyeY: 5,
      mouthX: 3,
      mouthY: 5,
    },
    gender: "female",
    age: "young adult",
    hairColor: "gray",
    eyeColor: "blue",
    vibe: "mysterious, serene, wise",
    clothing: "hooded robe",
  },
];
