import { MapData } from "@/map-processing/types/MapData.ts";
import getPathWithinAssetsDir from "@/fileIO/get-path-within-assets-dir.ts";
import { stringify } from "jsr:@std/yaml";

export default async function writeMapData(mapData: MapData): Promise<void> {
  const outputFilePath = getPathWithinAssetsDir(`maps/${mapData.name}.yaml`);
  const yamlData = stringify(mapData);
  await Deno.writeTextFile(outputFilePath, yamlData);
}

if (import.meta.main) {
  const mapData: MapData = {
    name: "Knights-Villagers-Bandits-10-3C-00-CE-3E",
    description:
      "A complex map featuring a mix of indoor and outdoor areas, with multiple staircases, walls, and points of interest including chests and stairs.",
    tmx: '<?xml version="1.0" encoding="UTF-8"?>\n<map version="1.0" orientation="orthogonal" renderorder="right-down" width="20" height="18" tilewidth="16" tileheight="16" nextobjectid="1">\n <tileset firstgid="1" name="3C00CE3E" tilewidth="16" tileheight="16">\n  <image source="Tilesets/3C00CE3E.png" width="512" height="512"/>\n </tileset>\n <layer name="Main" width="20" height="18">\n  <properties>\n   <property name="Main" value=""/>\n   <property name="Anims" value="_3CAnims"/>\n   <property name="ChapterID" value="<CHAPTERID>"/>\n   <property name="MapChangesID" value="Knights-Villagers-Bandits-10-3C-00-CE-3E_Changes"/>\n   <property name="MapID" value="Knights-Villagers-Bandits-10-3C-00-CE-3E_Map"/>\n   <property name="ObjectType" value="0x3C"/>\n   <property name="PaletteID" value="0xCE"/>\n   <property name="TileConfig" value="0x3E"/>\n  </properties>\n  <data encoding="base64" compression="zlib">\n   eJx1lMFLVFEUxs97jzCLBGtW+QckaRBaqW0NMkQj0H9AR4KUrKi/oBQEEWzZNhujGNFZuosZUqioBqJNW1G0shFXtun7uN/l3l60+HHmnnfOd885994pZGZnxKnUrAHq4AAsghHwVGvv/xTFlRKzj2bWD2qgFTpjsu/w7bPiaUfBA/BIud7/CxxKexs5X2ALsO+lw9pOS68Rxcd6B5G/HtVLvW3ofMXvn7Cvk8AJ7e9j18BDUIk0lhDXnIacFTAMnRuqrwPfTqbOliPdRq4OWq9Djc4o7y50mpkHpi2Q193SPGkrOZ0mxL8EK2ADrMPXhpkNIKYFXIOvnNM9BmqJs76Pe5FOTVojiBmHrYI9cA7rOmxRMWXFf7Bwdi3qZT5xeRPgJjiLmnZ0X+jjrIalMy6NTTCrmZwHF0A3eJa6c+TeQ+AVeGx/nw/vyCp8z1XvD82CuZfw7bv8/M57wRkN8jzBLdVAjYLuXXymrJOxC2BfOv2aw4RyWc99cAdMmZs79fy7uJq5O+XrnOM8wYDyZ8BbsCVN7jEpraK+ez3Wx7d5JQt6t6Pz87Mvap5V5bOmpdzcyJvEvaUe9e17rupceBZP1CP7Ltm/b4O9sce+zNmK3nlvVGNJZ8v3+MLCjL1GbxY02FtPzl4Eo2AvcW9nQ/fud+rqO56G/b0Ga7gcafh17G/H7yOwa+6+UfMbWE7C/j7e15Bfe8t4/vfwzl03N0fet67E6eV7+d/6D92xtrA=\n  </data>\n </layer>\n <layer name="Broken_Wall" width="20" height="18" visible="0">\n  <properties>\n   <property name="Height" value="1"/>\n   <property name="ID" value="0"/>\n   <property name="Width" value="2"/>\n   <property name="X" value="3"/>\n   <property name="Y" value="0"/>\n  </properties>\n  <data encoding="base64" compression="zlib">\n   eJxjYEAAYWYGhk9MDKNgFIyCUTAKBgEAAM3eAQs=\n  </data>\n </layer>\n <layer name="Left Chest" width="20" height="18" visible="0">\n  <properties>\n   <property name="Height" value="1"/>\n   <property name="ID" value="1"/>\n   <property name="Width" value="1"/>\n   <property name="X" value="1"/>\n   <property name="Y" value="1"/>\n  </properties>\n  <data encoding="base64" compression="zlib">\n   eJxjYKA+cKKBmaNgFIyCUTDSAABjRwBD\n  </data>\n </layer>\n <layer name="Right Chest" width="20" height="18" visible="0">\n  <properties>\n   <property name="Height" value="1"/>\n   <property name="ID" value="2"/>\n   <property name="Width" value="1"/>\n   <property name="X" value="19"/>\n   <property name="Y" value="10"/>\n  </properties>\n  <data encoding="base64" compression="zlib">\n   eJxjYBgFo2AU0AM4DbQDRsGQAwCXCABD\n  </data>\n </layer>\n <layer name="Door" width="20" height="18" visible="0">\n  <properties>\n   <property name="Height" value="2"/>\n   <property name="ID" value="3"/>\n   <property name="Width" value="2"/>\n   <property name="X" value="18"/>\n   <property name="Y" value="12"/>\n  </properties>\n  <data encoding="base64" compression="zlib">\n   eJxjYBgFo2AUjHSwjpGBQZCZeuZZAs0yo6J5IxUAANEhATk=\n  </data>\n </layer>\n</map>\n',
    height: 18,
    width: 20,
    terrainGrid: [
      [
        "Floor",
        "Floor",
        "Floor",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Stairs",
        "Plains",
        "Plains",
        "Forest",
      ],
      [
        "Floor",
        "Chest",
        "Floor",
        "Wall",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Stairs",
        "Road",
        "Plains",
        "Plains",
      ],
      [
        "Floor",
        "Floor",
        "Floor",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Stairs",
        "Plains",
        "Road",
        "Plains",
      ],
      [
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Stairs",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
      ],
      [
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
      ],
      [
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Brace",
        "Floor",
        "Brace",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Road",
        "Road",
      ],
      [
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Brace",
        "Stairs",
        "Brace",
        "Wall",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Sand",
        "Plains",
        "Forest",
      ],
      [
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Road",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Road",
        "Plains",
        "Plains",
        "Plains",
      ],
      [
        "Wall",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Road",
        "Road",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Wall",
      ],
      [
        "Wall",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Road",
        "Road",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Road",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Floor",
        "Floor",
      ],
      [
        "Wall",
        "Wall",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Floor",
        "Chest",
      ],
      [
        "Floor",
        "Stairs",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Hill",
        "Hill",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Floor",
        "Floor",
      ],
      [
        "Floor",
        "Floor",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Door",
      ],
      [
        "Floor",
        "Floor",
        "Wall",
        "Wall",
        "Plains",
        "Forest",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Stairs",
        "Floor",
        "Floor",
        "Floor",
      ],
      [
        "Floor",
        "Pillar",
        "Floor",
        "Wall",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Wall",
        "Wall",
        "Wall",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
      ],
      [
        "Floor",
        "Floor",
        "Floor",
        "Wall",
        "Plains",
        "Plains",
        "Road",
        "Road",
        "Plains",
        "Wall",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
      ],
      [
        "Pillar",
        "Floor",
        "Floor",
        "Wall",
        "Road",
        "Plains",
        "Plains",
        "Road",
        "Road",
        "Stairs",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Floor",
        "Pillar",
        "Floor",
        "Floor",
        "Floor",
      ],
      [
        "Floor",
        "Floor",
        "Floor",
        "Stairs",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Plains",
        "Stairs",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
        "Floor",
      ],
    ],
    pointsOfInterest: [
      {
        x: 16,
        y: 0,
        terrain: "Stairs",
      },
      {
        x: 1,
        y: 1,
        terrain: "Chest",
      },
      {
        x: 16,
        y: 1,
        terrain: "Stairs",
      },
      {
        x: 16,
        y: 2,
        terrain: "Stairs",
      },
      {
        x: 12,
        y: 3,
        terrain: "Stairs",
      },
      {
        x: 8,
        y: 6,
        terrain: "Stairs",
      },
      {
        x: 19,
        y: 10,
        terrain: "Chest",
      },
      {
        x: 1,
        y: 11,
        terrain: "Stairs",
      },
      {
        x: 16,
        y: 13,
        terrain: "Stairs",
      },
      {
        x: 9,
        y: 16,
        terrain: "Stairs",
      },
      {
        x: 3,
        y: 17,
        terrain: "Stairs",
      },
      {
        x: 9,
        y: 17,
        terrain: "Stairs",
      },
    ],
    areas: [
      {
        name: "Northern Building",
        description:
          "A large structure with multiple rooms and a central area, featuring walls and pillars.",
        subAreas: [
          {
            name: "Throne Room",
            description:
              "The main room with a red carpet and decorative pillars.",
            coordinates: {
              from: {
                x: 0,
                y: 0,
              },
              to: {
                x: 9,
                y: 8,
              },
            },
          },
          {
            name: "Treasure Room",
            description:
              "A room containing a chest, located in the northwest corner.",
            coordinates: {
              from: {
                x: 1,
                y: 1,
              },
              to: {
                x: 1,
                y: 1,
              },
            },
          },
          {
            name: "Staircase Area",
            description:
              "Area with multiple staircases leading to different levels.",
            coordinates: {
              from: {
                x: 16,
                y: 0,
              },
              to: {
                x: 16,
                y: 2,
              },
            },
          },
        ],
      },
      {
        name: "Southern Plains",
        description:
          "An open area with plains and forests, providing a contrast to the buildings.",
        subAreas: [
          {
            name: "Forest Edge",
            description:
              "A region filled with trees and bushes, providing cover.",
            coordinates: {
              from: {
                x: 16,
                y: 6,
              },
              to: {
                x: 19,
                y: 10,
              },
            },
          },
          {
            name: "Road",
            description:
              "A pathway connecting different areas, facilitating movement.",
            coordinates: {
              from: {
                x: 8,
                y: 6,
              },
              to: {
                x: 19,
                y: 10,
              },
            },
          },
        ],
      },
      {
        name: "Western Wing",
        description:
          "A section of the map with walls and a door leading to the outside.",
        subAreas: [
          {
            name: "Wall Corridor",
            description:
              "A narrow corridor lined with walls, leading to the main building.",
            coordinates: {
              from: {
                x: 0,
                y: 3,
              },
              to: {
                x: 3,
                y: 3,
              },
            },
          },
          {
            name: "Entrance Door",
            description:
              "A door leading to the outside, located at the western edge.",
            coordinates: {
              from: {
                x: 18,
                y: 12,
              },
              to: {
                x: 19,
                y: 13,
              },
            },
          },
        ],
      },
    ],
  };
  await writeMapData(mapData);
}

